../Debug/PuzzleGame.exe:Test.cpp PuzzleGame.cpp design.cpp
	g++ Test.cpp PuzzleGame.cpp design.cpp -Incurwin ncurwin/pdcurses.a -std=c++11 -lgdi32 -lcomdlg32 -o ../Debug/PuzzleGame.exe 
	../Debug/PuzzleGame.exe