# run.exe:misc/ncurarrowtest.cpp
# 	g++ misc/ncurarrowtest.cpp -Incurwin ncurwin/pdcurses.a -lgdi32 -lcomdlg32 -o run.exe 
# 	run.exe
run.exe:2021_g11_12/ashfaq/code/*.cpp
	g++  2021_g11_12/ashfaq/code/*.cpp -Incurwin ncurwin/pdcurses.a -lgdi32 -lcomdlg32 -o run.exe 
	run.exe
# run.exe:2021_g11_12/nader/*.cpp
# 	g++  2021_g11_12/nader/*.cpp -Incurwin ncurwin/pdcurses.a -lgdi32 -lcomdlg32 -o run.exe 
# 	run.exe
