build:
	dotnet build
clean:
	dotnet clean
restore:
	dotnet restore
watch:
	dotnet watch run --project formstest/formstest.fsproj
start:
	# dotnet run --project src/Main/Main.csproj
	dotnet run --project formstest/formstest.fsproj