@startuml

title DACSx - Component Interactions


package DACSx.UI.CockPit {
    interface Presenter{}
    class ConfigureScreen{}
    class AcquisitionScreen{}
    class HomeScreen{}
}

package DACSx.Domain{
    package DACSx.Domain.Configuration
    {
      interface DecoratorOrComposite{}
    }
    
    package DACSx.Domain.Acquisition{
      interface BufferedIO{}
      interface Subscriber
    }
}
ConfigureScreen .down.> DecoratorOrComposite: Uses
AcquisitionScreen .down.> Subscriber: Uses
AcquisitionScreen .down.> BufferedIO: Uses
HomeScreen .down.> Subscriber: Uses
HomeScreen .down.> BufferedIO: Uses
@enduml