[package]
name = "rmenu"
version = "0.1.0"
authors = ["John Alamina <john.alamina@netsells.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
