// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mathtest.proto

#include "mathtest.pb.h"
#include "mathtest.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mathtest {

static const char* MathTest_method_names[] = {
  "/mathtest.MathTest/sendRequest",
};

std::unique_ptr< MathTest::Stub> MathTest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MathTest::Stub> stub(new MathTest::Stub(channel));
  return stub;
}

MathTest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendRequest_(MathTest_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MathTest::Stub::sendRequest(::grpc::ClientContext* context, const ::mathtest::MathRequest& request, ::mathtest::MathReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendRequest_, context, request, response);
}

void MathTest::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::mathtest::MathRequest* request, ::mathtest::MathReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, std::move(f));
}

void MathTest::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mathtest::MathReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, std::move(f));
}

void MathTest::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::mathtest::MathRequest* request, ::mathtest::MathReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, reactor);
}

void MathTest::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mathtest::MathReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mathtest::MathReply>* MathTest::Stub::AsyncsendRequestRaw(::grpc::ClientContext* context, const ::mathtest::MathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mathtest::MathReply>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mathtest::MathReply>* MathTest::Stub::PrepareAsyncsendRequestRaw(::grpc::ClientContext* context, const ::mathtest::MathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mathtest::MathReply>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, false);
}

MathTest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MathTest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MathTest::Service, ::mathtest::MathRequest, ::mathtest::MathReply>(
          [](MathTest::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::mathtest::MathRequest* req,
             ::mathtest::MathReply* resp) {
               return service->sendRequest(ctx, req, resp);
             }, this)));
}

MathTest::Service::~Service() {
}

::grpc::Status MathTest::Service::sendRequest(::grpc::ServerContext* context, const ::mathtest::MathRequest* request, ::mathtest::MathReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mathtest

