######################################################################
# Automatically generated by qmake (3.1) Thu Sep 10 21:11:37 2020
######################################################################

TEMPLATE = app
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
SOURCES += q02.cpp
